const jwtServiceConfig = {
  authAuthenticationLogin: 'auth/authentication/login',
  authAuthenticationRefresh: '/auth/authentication/refresh',
  authAuthenticationRegenerateToken: '/auth/authentication/regnenerateToken',
  authAuthenticationLogout: '/auth/authentication/logout',
  authAuthenticationModifyUserPassword: '/auth/authentication/modifyUserPassword',
  authAuthenticationChangePassword: '/auth/authentication/changePassword',
  authAuthenticationForgotPassword: '/auth/authentication/forgotPassword',
  authAuthenticationLogin2FA: '/auth/authentication/login2FA',
  authUserViewAll: '/auth/user/viewAll',
  authUserAdd: '/auth/user/add',
  authUserEdit: '/auth/user/edit',
  authRoleViewAllDropdown: '/auth/role/viewAllDropdown',
  authUserActivateOrSuspend: '/auth/user/activateOrSuspend',
  authAuthenticationResetPassword: '/auth/authentication/resetPassword',
  authRoleViewAll: '/auth/role/viewAll',
  authRoleSaveRole: '/auth/role/saveRole',
  authRoleEditRole: '/auth/role/editRole',
  authPermissionGetPermissionsForRole: '/auth/permission/getPermissionsForRole',
  authPermissionViewAll: '/auth/permission/viewAll',
  authUserGroupAddOrEditUserGroup: '/auth/userGroup/addOrEditUserGroup',
  authUserGroupUpdateUserGroup: 'auth/userGroup/updateUserGroup',
  authUserGroupCreateUserGroup: 'auth/userGroup/createUserGroup',
  authUserGroupAddUser: '/auth/userGroup/addUsers',
  authUserGroupDeleteUser: '/auth/userGroup/deleteUser',
  authUserGroupGetUserGrpPermissions: '/auth/userGroup/getUserGrpPermissions',
  authUserGroupMapPermission: '/auth/userGroup/mapPermission',
  authUserGroupGetUserGroupDetails: '/auth/userGroup/getUserGroupDetails',
  authUserGroupGetAll: '/auth/userGroup/getAll',
  authUserGroupGetUserGrpUsers: '/auth/userGroup/getUserGrpUsers',
  authUserGroupAddUsers: '/auth/userGroup/addUsers',
  authUserGroupDeleteUsers: '/auth/userGroup/deleteUsers',
  fleUploadMultipleFile:'fle/uploadMultipleFile',
  fleGetAllUploadedFileDetails:'fle/getAllUploadedFileDetails',
  fleViewFileBase64:'fle/viewFileBase64'
};
export { jwtServiceConfig };
